# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Assessor' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Assessor

  pod 'Firebase/Core', '~> 6.2.0'
  pod 'Firebase/Auth', '~> 6.2.0'
  pod 'Firebase/Firestore', '~> 6.2.0'

#  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

#  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'AssessorTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Assessor-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Assessor-tvOS

  target 'Assessor-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
